services:
  adminer:
    container_name: adminer
    image: adminer:4.8.1
    restart: always
    ports:
      - "8081:8080"
    networks:
      - "tailored_social_network"

  smtp4dev:
    container_name: smtp4dev
    image: rnwood/smtp4dev:3.4.0
    restart: always
    ports:
      - "8082:80"
      - "25:25"
    networks:
      - "tailored_social_network"

networks:
  tailored_social_network:
    driver: bridge